(let ([x (read)])
(let ([y (read)])
(if (if (< x 1)
(eq? x 0)
(eq? x 2))
(+ y 2)
(+ y 10))))

;;; (let ([x 1]) (+ x 1))

;;; (let ([v 1])
;;; (let ([w 42])
;;; (let ([x (+ v 7)])
;;; (let ([y x])
;;; (let ([z (+ x w)])
;;; (+ z (- y)))))))